# Exported from Render on 2025-09-04T23:53:15Z
services:
- type: web
  name: go-task-manager
  runtime: docker
  repo: https://github.com/ryanegauthier/go-task-manager
  plan: free
  region: oregon
  dockerContext: .
  dockerfilePath: ./Dockerfile
  autoDeployTrigger: commit
  envVars:
  - key: GIN_MODE
    value: release
  - key: PORT
    value: "10000"
  - key: JWT_SECRET
    generateValue: true
  - key: CORS_ORIGIN
    value: "*"
  - key: CORS_METHODS
    value: "GET,POST,PUT,DELETE,OPTIONS"
  - key: CORS_HEADERS
    value: "Origin,Content-Type,Content-Length,Accept-Encoding,X-CSRF-Token,Authorization"
  healthCheckPath: /
version: "1"
